services:
  bluga:
    image: cavdy/bluga
    container_name: bluga
    env_file: .env
    restart: unless-stopped
    ports:
      - '50921:50921'
    volumes:
      - /path/uploads/:/usr/src/app/build/public/uploads
      - /path/themes/:/usr/src/app/build/tools/themes
